# 配置Gradle使用指定的Java版本和供应商
org.gradle.java.installations.paths=~/local/openjdk/jdk-25.jdk/Contents/Home
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.fromEnv=JAVA_HOME

# gradle.properties
#systemProp.http.proxyHost=
#systemProp.http.proxyPort=8080
#systemProp.https.proxyHost=
#systemProp.https.proxyPort=8080

# 如果代理需要认证
#systemProp.https.proxyUser=
#systemProp.https.proxyPassword=