server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    enabled: true
    path: /spring-boot-serializer.html
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8080/swagger-ui/index.html
    disable-swagger-default-url: on