server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/moon?currentSchema=moon_transaction
    username: moon
    password: moon
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8080/swagger-ui/index.html
    disable-swagger-default-url: on
knife4j:
  enable: true
  setting:
    language: zh_cn