server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-boot-captcha
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    # password: your_password # 如果有密码，请取消注释并设置
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    root: INFO
    org.moonzhou.captcha: DEBUG

# Captcha configuration
captcha:
  # 存储方式：可选枚举值为 'session'（默认）或 'redis'
  storage: redis  # ✅ 可选值: session, redis