server:
  port: 8080

spring:
  data:
    redis:
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间
      jedis:
        pool: #连接池配置
          max-active: 8 #连接池最大连接数
          max-wait: -1 #连接池最大阻塞等待时间
          max-idle: 8 #连接池中的最大空闲连接数
          min-idle: 0 #连接池中的最小空闲连接数
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    enabled: true
    path: /moon-redis-om.html
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8080/swagger-ui/index.html
    disable-swagger-default-url: on