spring:
  application:
    name: spring-boot-mysql-fulltext
  datasource:
    url: jdbc:mysql://localhost:3306/moon_fulltext?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE