create table users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    email varchar(128) not null unique,
    created_at timestamp not null
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    price decimal(12,2) not null
);

create table orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    total_amount decimal(12,2) not null,
    status varchar(24) not null,
    created_at timestamp not null,
    constraint fk_orders_user foreign key (user_id) references users(id)
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity int not null,
    unit_price decimal(12,2) not null,
    line_amount decimal(12,2) not null,
    constraint fk_items_order foreign key (order_id) references orders(id),
    constraint fk_items_product foreign key (product_id) references products(id)
);
