package org.moonzhou.springcloudlearning.webservice.consumer.webservice.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-09-18T16:55:47.374+08:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "TestServerImplService",
                  wsdlLocation = "http://localhost:8081/spring-cloud-learning/webservice/provider/moonzhou-webservice/api?wsdl",
                  targetNamespace = "http://impl.service.provider.webservice.springcloudlearning.moonzhou.org/")
public class TestServerImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.provider.webservice.springcloudlearning.moonzhou.org/", "TestServerImplService");
    public final static QName TestServerImplPort = new QName("http://impl.service.provider.webservice.springcloudlearning.moonzhou.org/", "TestServerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/spring-cloud-learning/webservice/provider/moonzhou-webservice/api?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestServerImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/spring-cloud-learning/webservice/provider/moonzhou-webservice/api?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServerImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestServerImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestServerImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestServerImpl
     */
    @WebEndpoint(name = "TestServerImplPort")
    public TestServerImpl getTestServerImplPort() {
        return super.getPort(TestServerImplPort, TestServerImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestServerImpl
     */
    @WebEndpoint(name = "TestServerImplPort")
    public TestServerImpl getTestServerImplPort(WebServiceFeature... features) {
        return super.getPort(TestServerImplPort, TestServerImpl.class, features);
    }

}
